てきすとぼっくすimport type { NextPage, GetServerSidePropsContext } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { ValorantCharacter } from '../../src/constants/CharacterList'
import styles from '../../styles/Home.module.css'

type CharacterList = { data: ValorantCharacter[]}

const AbilityCalculator: NextPage<CharacterList> = (characterList) => {
  const [text, setText] = useState('')

  return (
    <div className={styles.container}>
      <Head>
        <title>VALORANT アビリティ計算機</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input
          value={text}
          onChange={(event) => setText(event.target.value)}
        ></input>
        <p>{text}</p>
        <ol>
          {characterList.data.map((character) => (
            <li>{character.name}</li>
          ))}
        </ol>
      </main>
    </div>
  )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const host: string = context.req.headers.host || 'localhost:3000'
  let protocol: string
  if (/^localhost/.test(host)) {
    protocol = 'http'
  } else {
    protocol = 'https'
  }
  const res: ValorantCharacter[] = await fetch(`${protocol}://${host}/api/valorant/character/get`)
    .then(res => {
      return res.json()
    })
    .catch(err => {
      return []
    })
  // console.log(res)
  const r: CharacterList = {data: res}
  return { props: r }
}

export default AbilityCalculator
