import type { NextPage, GetServerSidePropsContext } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState, useRef, useEffect } from 'react'
import { ValorantCharacter } from '../../src/constants/valorant/CharacterList'
import styles from '../../styles/Home.module.css'

type CharacterList = { data: ValorantCharacter[]}

const AbilityCalculator: NextPage<CharacterList> = (characterList) => {
  const [text, setText] = useState('')

  const characterListRef = useRef(null)
  const [selectedCharacter, setSelectedCharacter] = useState()

  const setCharacterList = () => {
    console.log(characterList)
    let i = 0
    characterList.data.map((character) => {
      const option = document.createElement('option')
      option.value = `${i}`
      option.text = character.name
      characterListRef.current.appendChild(option)
      i += 1
    })
  }

  const selectCharacter = (e) => {
    console.log(`選択されたvalue: ${e.target.value}`)
    setSelectedCharacter(e.target.value)
  }

  useEffect(() => {
    setCharacterList()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>VALORANT アビリティ計算機</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>VALORANT 購入フェーズ計算機</h1>
        現在のクレジット残高 (最大9,000)
        <input
          value={text}
          onChange={(event) => setText(event.target.value)}
        ></input>
        <p>入力した値: {text}</p>

        <p>キャラクター選択</p>
        <label>
          <select ref={characterListRef} value={selectedCharacter} onChange={selectCharacter}></select>
        </label>
        <p>選択したキャラのvalue: {selectedCharacter}</p>
      </main>
    </div>
  )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const host: string = context.req.headers.host || 'localhost:3000'
  let protocol: string
  if (/^localhost/.test(host)) {
    protocol = 'http'
  } else {
    protocol = 'https'
  }
  const res: ValorantCharacter[] = await fetch(`${protocol}://${host}/api/valorant/character/get`)
    .then(res => {
      return res.json()
    })
    .catch(err => {
      return []
    })
  // console.log(res)
  const r: CharacterList = {data: res}
  return { props: r }
}

export default AbilityCalculator
